name: Generate Conversion Tokens

on:
  [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install wget numpy opencv
        
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            python3 --version
            python3 generators/token/generate.py
        
      - name: Commit to the repo
        run: |
          git config --global user.name "JulianWww/generator"
          git config --global user.email "generator[bot]@JulianWww.github.io"
          git add .
          # Force the build to succeed, even if no files were changed
          git commit -m 'regenerated tokens' || true
