name: Generate Conversion Tokens

on:
  [push]
  paths:
  - generators/token

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r wget numpy opencv
        
    - name: Generate images
      run: |
        python3 --version
        python3 generators/token/generate.py
        
    - name: Commit to the repo
      run: |
        git config --global user.name "JulianWww/generator"
        git config --global user.email "generator[bot]@JulianWww.github.io"
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'regenerated tokens' || true
        git push
